### ISSUE TITLE
decide on API topic

### ISSUE THREAD

**Issue by chphoom** [comp426-2022-fall/a99-Team18#2]

**Comment by chphoom** [comment]
some ideas:
-a task tracker that u load up with errands or chores or small tasks and it randomly selects one and reads like your being given a side quest

-an app using the MTG API that allows you to play test a deck in a simulated game (except the program is randomly playing cards)

-a game entirely played through ascii art

**Comment by chphoom** [comment]
another idea:

-a magic 8 ball simulator

**Comment by akarki123** [comment]
I think the MTG app could be cool but I feel like it would get complex really fast, I like the idea of the task tracker or even the magic 8 ball simulator

**Comment by chphoom** [comment]
So the consensus is on moving forward with a minigame app !!
